spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot-mp01?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:cn/king/demo01/mapper/*Mapper.xml
  type-aliases-package: cn.king.demo01.model


